version: 2
jobs:
  build:
    docker:
      - image: centos:7
    steps:
      - checkout
      - run:
          name: Copy artifacts
          command: |
            yum install -y wget tar git make gcc gcc-c++
            wget https://github.com/Kitware/CMake/releases/download/v3.16.2/cmake-3.16.2-Linux-x86_64.tar.gz
            tar -xf cmake-3.16.2-Linux-x86_64.tar.gz
            export PATH=$PWD/cmake-3.16.2-Linux-x86_64/bin:$PATH
            git clone https://github.com/llvm/llvm-project.git -b release/7.x
            mkdir llvm-build
            cd llvm-build
            cmake -DCMAKE_BUILD_TYPE=Release -DLLVM_TARGETS_TO_BUILD=X86 -DLLVM_ENABLE_PROJECTS="clang;libcxx;libcxxabi;libunwind;compiler-rt;lld" -DCMAKE_INSTALL_PREFIX=$PWD/../llvm ../llvm-project/llvm
            cmake --build . -t install -j 8
            cd ..
            cd llvm/ && tar -zcvf ../llvm.tar.gz . && cd - 
      - store_artifacts:
          path: llvm.tar.gz
          destination: /
workflows:
  version: 2
  build:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build